Import('env')

lib_env = env.Clone()

lib_env.ParseConfig("pkg-config gtest --cflags")
lib_env.Library(
    'infectious',
    ['addmul.cpp', 'berlekamp_welch.cpp', 'math.cpp'])

test_env = env.Clone()
test_env.ParseConfig("pkg-config gtest_main --cflags --libs")
test_env.Append(
    LIBPATH='.',
    LIBS=['infectious'])
test_env.Program(
    'infectious-test',
    Glob('*_test.cpp'))
